/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorgui;

/**
 *
 * @author Nisrina Izdihar
 */
public class KalkulatorGUI extends javax.swing.JFrame {
    String angka = "";
    double jumlah,angka1,angka2;
    int pilih;
    

    /**
     * Creates new form Latihan5
     */
    public KalkulatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varHasil = new javax.swing.JTextField();
        ClearAll = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        buttonBagi = new javax.swing.JButton();
        buttonKali = new javax.swing.JButton();
        Tujuh = new javax.swing.JButton();
        Delapan = new javax.swing.JButton();
        Sembilan = new javax.swing.JButton();
        buttonKurang = new javax.swing.JButton();
        Empat = new javax.swing.JButton();
        Lima = new javax.swing.JButton();
        Enam = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        Satu = new javax.swing.JButton();
        Dua = new javax.swing.JButton();
        Tiga = new javax.swing.JButton();
        buttonSamadengan = new javax.swing.JButton();
        buttonPersen = new javax.swing.JButton();
        Nol = new javax.swing.JButton();
        buttonKoma = new javax.swing.JButton();
        Pangkat = new javax.swing.JButton();
        Akar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR");
        getContentPane().setLayout(null);

        varHasil.setEditable(false);
        varHasil.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        varHasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(varHasil);
        varHasil.setBounds(10, 10, 280, 80);

        ClearAll.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ClearAll.setText("AC");
        getContentPane().add(ClearAll);
        ClearAll.setBounds(10, 110, 140, 50);

        Clear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(80, 160, 70, 50);

        buttonBagi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonBagi.setText("/");
        buttonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBagiActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBagi);
        buttonBagi.setBounds(150, 160, 70, 50);

        buttonKali.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonKali.setText("x");
        buttonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKali);
        buttonKali.setBounds(220, 160, 70, 50);

        Tujuh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tujuh.setText("7");
        Tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuhActionPerformed(evt);
            }
        });
        getContentPane().add(Tujuh);
        Tujuh.setBounds(10, 210, 70, 50);

        Delapan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Delapan.setText("8");
        Delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelapanActionPerformed(evt);
            }
        });
        getContentPane().add(Delapan);
        Delapan.setBounds(80, 210, 70, 50);

        Sembilan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Sembilan.setText("9");
        Sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SembilanActionPerformed(evt);
            }
        });
        getContentPane().add(Sembilan);
        Sembilan.setBounds(150, 210, 70, 50);

        buttonKurang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonKurang.setText("-");
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKurang);
        buttonKurang.setBounds(220, 210, 70, 50);

        Empat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Empat.setText("4");
        Empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpatActionPerformed(evt);
            }
        });
        getContentPane().add(Empat);
        Empat.setBounds(10, 260, 70, 50);

        Lima.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lima.setText("5");
        Lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimaActionPerformed(evt);
            }
        });
        getContentPane().add(Lima);
        Lima.setBounds(80, 260, 70, 50);

        Enam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Enam.setText("6");
        Enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnamActionPerformed(evt);
            }
        });
        getContentPane().add(Enam);
        Enam.setBounds(150, 260, 70, 50);

        buttonTambah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonTambah.setText("+");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTambah);
        buttonTambah.setBounds(220, 260, 70, 50);

        Satu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Satu.setText("1");
        Satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SatuActionPerformed(evt);
            }
        });
        getContentPane().add(Satu);
        Satu.setBounds(10, 310, 70, 50);

        Dua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Dua.setText("2");
        Dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuaActionPerformed(evt);
            }
        });
        getContentPane().add(Dua);
        Dua.setBounds(80, 310, 70, 50);

        Tiga.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Tiga.setText("3");
        Tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TigaActionPerformed(evt);
            }
        });
        getContentPane().add(Tiga);
        Tiga.setBounds(150, 310, 70, 50);

        buttonSamadengan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonSamadengan.setText("=");
        buttonSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSamadenganActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSamadengan);
        buttonSamadengan.setBounds(220, 310, 70, 100);

        buttonPersen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonPersen.setText("%");
        buttonPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersenActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPersen);
        buttonPersen.setBounds(150, 110, 70, 50);

        Nol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Nol.setText("0");
        Nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NolActionPerformed(evt);
            }
        });
        getContentPane().add(Nol);
        Nol.setBounds(10, 360, 140, 50);

        buttonKoma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buttonKoma.setText(",");
        buttonKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKomaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKoma);
        buttonKoma.setBounds(150, 360, 70, 50);

        Pangkat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Pangkat.setText("^");
        getContentPane().add(Pangkat);
        Pangkat.setBounds(10, 160, 70, 50);

        Akar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Akar.setText("√");
        getContentPane().add(Akar);
        Akar.setBounds(220, 110, 70, 50);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 450);

        setBounds(0, 0, 316, 459);
    }// </editor-fold>//GEN-END:initComponents

    private void SatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SatuActionPerformed
        // TODO add your handling code here:
        angka += "1";
        varHasil.setText(angka);
    }//GEN-LAST:event_SatuActionPerformed

    private void DuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuaActionPerformed
        // TODO add your handling code here:
        angka += "2";
        varHasil.setText(angka);
    }//GEN-LAST:event_DuaActionPerformed

    private void TigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TigaActionPerformed
        // TODO add your handling code here:
         angka += "3";
        varHasil.setText(angka);
    }//GEN-LAST:event_TigaActionPerformed

    private void EmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpatActionPerformed
        // TODO add your handling code here:
         angka += "4";
        varHasil.setText(angka);
    }//GEN-LAST:event_EmpatActionPerformed

    private void LimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimaActionPerformed
        // TODO add your handling code here:
         angka += "5";
        varHasil.setText(angka);
    }//GEN-LAST:event_LimaActionPerformed

    private void EnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnamActionPerformed
        // TODO add your handling code here:
         angka += "6";
        varHasil.setText(angka);
    }//GEN-LAST:event_EnamActionPerformed

    private void TujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuhActionPerformed
        // TODO add your handling code here:
         angka += "7";
        varHasil.setText(angka);
    }//GEN-LAST:event_TujuhActionPerformed

    private void DelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelapanActionPerformed
        // TODO add your handling code here:
         angka += "8";
        varHasil.setText(angka);
    }//GEN-LAST:event_DelapanActionPerformed

    private void SembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SembilanActionPerformed
        // TODO add your handling code here:
         angka += "9";
        varHasil.setText(angka);
    }//GEN-LAST:event_SembilanActionPerformed

    private void NolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NolActionPerformed
        // TODO add your handling code here:
         angka += "0";
        varHasil.setText(angka);
    }//GEN-LAST:event_NolActionPerformed

    private void buttonKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKomaActionPerformed
        // TODO add your handling code here:
        angka += ".";
        varHasil.setText(angka);
    }//GEN-LAST:event_buttonKomaActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        varHasil.setText("");
        angka1 = 0.0;
        angka2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_ClearActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        varHasil.setText("+");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        varHasil.setText("-");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_buttonKurangActionPerformed

    private void buttonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaliActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        varHasil.setText("x");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_buttonKaliActionPerformed

    private void buttonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBagiActionPerformed
        // TODO add your handling code here:
        angka1 = Double.parseDouble(angka);
        varHasil.setText("/");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_buttonBagiActionPerformed

    private void buttonSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSamadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 + angka2;
                angka = Double.toString(jumlah);
                varHasil.setText(angka);
                break;
            case 2 : 
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 - angka2;
                angka = Double.toString(jumlah);
                varHasil.setText(angka);
                break;
            case 3 :
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 * angka2;
                angka = Double.toString(jumlah);
                varHasil.setText(angka);
                break;
            case 4 : 
                angka2 = Double.parseDouble(angka);
                jumlah = angka1 / angka2;
                angka = Double.toString(jumlah);
                varHasil.setText(angka);
                break;
                default:
                break;
        }
    }//GEN-LAST:event_buttonSamadenganActionPerformed

    private void buttonPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPersenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Akar;
    private javax.swing.JButton Clear;
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton Delapan;
    private javax.swing.JButton Dua;
    private javax.swing.JButton Empat;
    private javax.swing.JButton Enam;
    private javax.swing.JButton Lima;
    private javax.swing.JButton Nol;
    private javax.swing.JButton Pangkat;
    private javax.swing.JButton Satu;
    private javax.swing.JButton Sembilan;
    private javax.swing.JButton Tiga;
    private javax.swing.JButton Tujuh;
    private javax.swing.JButton buttonBagi;
    private javax.swing.JButton buttonKali;
    private javax.swing.JButton buttonKoma;
    private javax.swing.JButton buttonKurang;
    private javax.swing.JButton buttonPersen;
    private javax.swing.JButton buttonSamadengan;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField varHasil;
    // End of variables declaration//GEN-END:variables
}
